on:
  push:
    tags:
      - 'v*'
    branches:
      - master
      - next
  pull_request:
    branches:
      - master

permissions:
  contents: write

name: Build robot

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        java: [ 8, 11, 17, 21 ]
    name: Java ${{ matrix.java }}
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v5.0.0
        with:
          submodules: true
          fetch-depth: 0 # To make git describe give the intended output
          fetch-tags: true
      - name: Setup java
        uses: actions/setup-java@v5.0.0
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven
      - name: Set SSH key
        if: github.event_name != 'pull_request'
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Add host key
        if: github.event_name != 'pull_request'
        run: ssh-keyscan mvn.javacard.pro >> ~/.ssh/known_hosts
      - name: Run Maven for capfile
        if: matrix.java != 8
        run: ./mvnw -B --no-transfer-progress -T1C -U verify
      - name: Run ANT tests
        run: ant test dist
      - name: Get SHA-256 of ant-javacard.jar
        run: echo "JARSUM=$(shasum -a 256 --tag ant-javacard.jar)" >> "$GITHUB_ENV"
      - name: Deploy package or snapshot
        if: github.event_name != 'pull_request' && matrix.java == '11'
        run: ./mvnw -B --no-transfer-progress -U deploy
      - name: Upload
        if: github.event_name != 'pull_request' && matrix.java == '11'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ant-javacard.jar
          path: ant-javacard.jar
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v') && matrix.java == '11'
        id: create_release
        uses: softprops/action-gh-release@v2.3.3
        with:
          files: |
            ant-javacard.jar
          fail_on_unmatched_files: true
          body: "Release ${{ github.ref_name }}, `${{ env.JARSUM }}` (built with JDK-11)"
          prerelease: true # manually promoted
